configuration:
  database:
    name: mastodon-pool-test
    user: mastodon-test
  localDomain: test.toot.community
  redis:
    host: redis-haproxy.haproxy.svc.cluster.local
    database: 5
  s3:
    aliasHost: test-files.toot.community/static
    bucket: static
    endpoint: https://test-files-toot-community.ams3.digitaloceanspaces.com

web:
  domain: test.toot.community
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
  podDisruptionBudget:
    enabled: false

statistics:
  enabled: false

translations:
  enabled: false

streaming:
  replicaCount: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
  podDisruptionBudget:
    enabled: false

sidekiq:
  workers:
    - name: generic
      concurrency: 5
      queues:
        - default
        - ingress
        - pull
        - push
        - mailers
        - scheduler
      resources:
        requests:
          cpu: 1m
          memory: 1Mi

ingress:
  host: test.toot.community
  tls:
    - hosts:
        - test.toot.community
      secretName: cf-origin-certificate-tls

jobs:
  annotations: {}
  cleanupMedia:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
  psqlBackup:
    enabled: false
  removePreviewCards:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 1Mi

onePassword:
  - name: cf-origin-certificate-tls
    itemPath: vaults/dhwqy3tub7zdwf2zj6cv4lprlu/items/hpm4njgmdollluy5b4isc2zpgq
  - suffix: secrets-env
    itemPath: vaults/dhwqy3tub7zdwf2zj6cv4lprlu/items/kvd2a5lukn6ksm6ybkdv23zhaa

keda:
  web:
    enabled: false
  workers:
    enabled: false
